/**
 * Assembles the served browser half.
 *
 * `tsc -p tsconfig.client.json` compiles `client/main.ts` to `client/main.js` as a
 * classic script, and `scripts/generate-sounds.ts` writes the audio data module
 * `client/sounds.generated.js` — also a plain script. The web shell fetches ONE
 * classic script per plugin, so this script concatenates both into
 * `client/client.js` inside a single IIFE: the sound table stays a closure
 * binding instead of a page global, and nothing can collide with another bundle
 * sharing the combo response.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const strip = (text) => text.replace(/^\/\/# sourceMappingURL=.*$/gm, '').trimEnd();

const sounds = strip(readFileSync(join(ROOT, 'client', 'sounds.generated.js'), 'utf8'));
const body = strip(readFileSync(join(ROOT, 'client', 'main.js'), 'utf8'));

const banner = [
  '"use strict";',
  '/*',
  ' * dsh-session-chime browser half — generated by scripts/build-client.mjs.',
  ' * Edit client/main.ts and client/sounds.generated.js (via scripts/generate-sounds.ts);',
  ' * this file is the concatenated, served artifact.',
  ' */',
].join('\n');

writeFileSync(join(ROOT, 'client', 'client.js'), `${banner}\n(function () {\n${sounds}\n\n${body}\n})();\n`);
console.log('wrote client/client.js');
